package com.tripian.trpcore.util

object LanguageConst {
    const val CONTINUE = "trips.createNewTrip.form.continue"
    const val PREVIOUS = "trips.createNewTrip.form.previous"
    const val CANCEL = "trips.createNewTrip.form.cancel"
    const val CONFIRM = "confirm"
    const val WARNING = "warning"
    const val SUCCESS = "success"
    const val ERROR = "error"
    const val UPDATE = "user.profile.submit"
    const val DELETE = "cg_delete"
    const val CHANGE_PSW = "user.profile.changePassword.button"
    const val PROFILE = "user.profile"
    const val TRAVEL_COMPANIONS = "user.travelCompanions.title"
    const val CANCEL_RESERVATION = "trips.myTrips.localExperiences.tourDetails.cancelReservation"
    const val MAKE_RESERVATION = "make_reservation"
    const val GLOBAL_RATING = "global_rating"
    const val MATCH = "trips.myTrips.itinerary.step.poi.match"
    const val PART_OF_DAY = "trips.myTrips.itinerary.step.poi.partOfDay"
    const val COVERING = "trips.myTrips.itinerary.step.poi.tourTicket.tour.covering"
    const val NO_OFFERS_FOUND = "trips.myTrips.itinerary.offers.emptyOffersMessage"
    const val NO_RESULT_IN_AREA = "no_results_in_area"
    const val FROM = "trips.myTrips.itinerary.customPoiModal.visitTime.from"
    const val TO = "trips.myTrips.itinerary.customPoiModal.visitTime.to"
    const val OFFER_CLAIM = "notification.offerOptIn.title"
    const val DATE = "reservation.date"
    const val ATTRACTIONS = "trips.myTrips.exploreMore.categories.attractions"
    const val RESTAURANTS = "trips.myTrips.exploreMore.categories.restaurants"
    const val CAFES = "trips.myTrips.exploreMore.categories.cafes"
    const val NIGHTLIFE = "trips.myTrips.exploreMore.categories.nightlife"
    const val MUST_TRY = "trips.myTrips.itinerary.step.poi.mustTry.title"
    const val COMMON_ERROR = "trips.toursAndTickets.error.anErrorOccured"
    const val NO_NETWORK = "no_network"
    const val LANGUAGE = "language"
    const val NAME_REQUIRED = "name_is_required"
    const val COMPANION_TITLE_REQUIRED = "select_title_for_your_companion"
    const val TYPE_AGE = "type_age"
    const val ERROR_ENTER_EMAIL = "trips.myTrips.localExperiences.tourDetails.pleaseEnterYourEmail"
    const val ERROR_EMAIL_FORMAT = "auth.login.error.emailFormat"
    const val ERROR_PASSWORD = "auth.login.error.password"
    const val ERROR_PASSWORD_EQUAL = "auth.resetPassword.error.passwordsNotEqual"
    const val ERROR_ENTER_FIRST_NAME = "trips.myTrips.localExperiences.tourDetails.pleaseEnterYourFirstName"
    const val ERROR_ENTER_LAST_NAME = "trips.myTrips.localExperiences.tourDetails.pleaseEnterYourLastName"
    const val ERROR_TOE = "auth.register.error.acceptTheTermsOfUse"
    const val SUCCESS_PSW_CHANGE = "user.profile.changePassword.success"
    const val SELECT_ARRIVAL_HOUR = "select_arrival_hour"
    const val SELECT_DEPARTURE_HOUR = "select_departure_hour"
    const val DOU_YOU_CONFIRM = "trips.myTrips.itinerary.offers.payment.doYouConfirm"
    const val PROFILE_UPDATED = "user.profile.success"
    const val DELETE_USER = "delete_account_confirm"
    const val DELETE_MY_ACCOUNT = "user.deleteUser.deleteMyAccount"
    const val ENTER_PSW = "enter_password"
    const val ENTER_EMAIL_HASH = "enter_email_code"
    const val ENTER_NEW_PSW = "enter_new_password"
    const val ENTER_EMAIL_RESET = "enter_email_reset"
    const val PASSWORD_CHANGED = "password_changed"
    const val REDIRECT_CONFIRM = "redirect_confirmation"
    const val DELETE_TRIP_QUESTION = "trips.deleteTrip.question"
    const val PLACES = "trips.myTrips.itinerary.places"
    const val NO_RESULT_FOUND = "trips.myTrips.exploreMore.noResultsFound"
    const val FAMILY_MEMBER = "family_member"
    const val WORK_COLLEAGUE = "work_colleague"
    const val FRIEND = "friend"
    const val NO_PAST_TRIPS = "no_past_trips"
    const val HELLO = "user.hi"
    const val CHILDREN = "trips.toursAndTickets.children.label"
    const val ADULTS = "trips.toursAndTickets.adults.label"
    const val NO_RECOMMENDATIONS_ARRIVAL = "no_recommendations_arrival"
    const val NO_RECOMMENDATIONS_DEPARTURE = "no_recommendations_departure"
    const val ADD_PLACES = "trips.myTrips.itinerary.error.emptyMesssage"
    const val LOCATION_PERMISSION = "location_permission"
    const val ENABLE_LOCATION_PERMISSION = "enable_location"
    const val ERROR_LOCATION_PERMISSION = "location_permission_denied"
    const val SETTINGS = "common.button.settings"
    const val BACK = "common.button.back"
    const val NOT_IN_CITY = "your_current_location_is_not_in_city"
    const val ENTER_TWO_CHARS = "trips.myTrips.exploreMore.placeholder"
    const val FAVORITES = "trips.myTrips.itinerary.favorites.title"
    const val NO_FAVORITES = "trips.myTrips.itinerary.favorites.emptyMessage"
    const val WHERE_TO_TRY = "where_to_try"
    const val MY_OFFERS = "trips.myTrips.itinerary.offers.title"
    const val MY_OFFERS_NO_OFFER = "trips.myTrips.itinerary.offers.myOffers.emptyOffersMessage"
    const val UPCOMING_TRIPS = "trips.myTrips.upComingTrips.title"
    const val PAST_TRIPS = "trips.myTrips.pastTrips.title"
    const val USER = "user.title"
    const val SUPPORT = "support.title"
    const val TOE = "support.termsOfUse.title"
    const val PP = "support.privacyPolicy.title"
    const val ABOUT_TRIPIAN = "support.aboutTripian.title"
    const val TRADEMARK = "landing.feelLikeALocalWhereverYouGo.title"
    const val LOG_OUT = "logout"
    const val DAYS = "trips.days"
    const val DAY = "trips.myTrips.itinerary.day"
    const val SEARCH = "search"
    const val WHERE_START = "trips.createNewTrip.form.travelerInfo.accommodation.label"
    const val HOTEL_PLACEHOLDER = "trips.createNewTrip.form.travelerInfo.accommodation.placeholder"
    const val WHO_TRAVEL_WITH = "trips.createNewTrip.form.travelerInfo.companion.label"
    const val ENTER_START = "enter_hotel_address"
    const val BUY_TICKETS_TOURS = "buy_tickets_tours"
    const val PLANNER = "planner"
    const val EXPERIENCES = "trips.myTrips.itinerary.experiences"
    const val SEARCH_THIS_AREA = "trips.myTrips.itinerary.searchThisArea.title"
    const val CLEAR_SEARCH = "trips.myTrips.itinerary.searchThisArea.clear"
    const val ENTER_PASSWORD = "auth.login.password.placeholder"
    const val ENTER_NEW_PASSWORD = "auth.resetPassword.password.placeholder"
    const val RETYPE_NEW_PASSWORD = "auth.resetPassword.confirmPassword.placeholder"
    const val NO_COMPANION = "user.travelCompanions.emptyMessage"
    const val ADD_TRAVELERS = "add_travelers"
    const val CREATE_NEW = "trips.createNewTrip.form.travelerInfo.companion.submit"
    const val WHERE_YOU_GO = "trips.createNewTrip.form.destination.city.label"
    const val DESTINATION_PLACEHOLDER = "trips.createNewTrip.form.destination.city.placeholder"
    const val SELECT_DATES = "trips.createNewTrip.form.destination.dates"
    const val SELECT_HOURS = "trips.createNewTrip.form.destination.hours"
    const val ARRIVAL = "arrival"
    const val DEPARTURE = "departure"
    const val ADD_COMPANION = "add_companion"
    const val CREATE_COMPANION_PROFILE = "create_companion_profile"
    const val CHANGE_DAY = "change_day"
    const val EMAIL = "auth.register.email.label"
    const val EMAIL_PLACEHOLDER = "auth.register.email.placeholder"
    const val DATE_OF_BIRTH = "user.profile.dateOfBirth"
    const val FORGOT_PASS = "auth.login.forgotPassword"
    const val FORGOT_PASS_DESC = "enter_email_reset"
    const val CODE = "code"
    const val SEND_MAIL = "auth.forgotPassword.submit"
    const val SEND_MAIL_AGAIN = "send_email_again"
    const val RESET_PSW = "auth.resetPassword.title"
    const val ITINERARY = "itinerary"
    const val LOGIN = "auth.login.submit"
    const val LOGIN_TITLE = "auth.login.title"
    const val GOOGLE_LOGIN = "auth.login.google"
    const val OR = "auth.login.or"
    const val DONT_HAVE_ACCOUNT = "auth.login.account"
    const val REGISTER_NOW = "auth.login.registerNow"
    const val EDIT_TRIP = "trips.editTrip.title"
    const val DELETE_TRIP = "trips.deleteTrip.title"
    const val COMPANION_SUBTITLE = "trips.createNewTrip.form.travelerInfo.companion.description"
    const val TITLE = "user.travelCompanions.companionTitle"
    const val NAME = "user.travelCompanions.companionName"
    const val AGE = "user.travelCompanions.companionAge"
    const val TYPE_NAME = "type_name"
    const val REGISTER = "user.register"
    const val ENTER_FIRST_NAME = "user.profile.firstName.placeholder"
    const val ENTER_LAST_NAME = "user.profile.lastName.placeholder"
    const val SIGN_UP_NOW = "auth.register.submit"
    const val ALL = "all"
    const val REPLACE = "trips.myTrips.itinerary.step.thumbs.replace.title"
    const val DURATION_CAR = "duration_format"
    const val DURATION_WALK = "walk_duration_format"
    const val BOOK_A_RIDE = "trips.myTrips.itinerary.direction"
    const val ALTERNATIVES = "trips.myTrips.itinerary.step.thumbs.replace.alternativeLocations"
    const val APPLY = "trips.myTrips.itinerary.step.addToItinerary.submit.apply"
    const val REMOVE = "trips.myTrips.itinerary.step.thumbs.remove"
    const val SELECT_CATEGORY = "select_category"
    const val PLEASE_SELECT_CATEGORY = "trips.myTrips.exploreMore.selectCategory"
    const val ESTIMATED_DURATION = "trips.myTrips.itinerary.step.addToItinerary.estimatedDuration"

    const val MONDAY = "monday"
    const val TUESDAY = "tuesday"
    const val WEDNESDAY = "wednesday"
    const val THURSDAY = "thursday"
    const val FRIDAY = "friday"
    const val SATURDAY = "saturday"
    const val SUNDAY = "sunday"
    const val CLOSED = "closed"



    //Create Trip
    const val CREATE_TRIP = "trips.createNewTrip.form.submit"
    const val DESTINATION = "trips.createNewTrip.stepHeaders.destination"
    const val TRAVELER_INFO = "trips.createNewTrip.stepHeaders.travelerInfo"
    const val ITINERARY_PROFILE = "trips.createNewTrip.stepHeaders.itineraryProfile"
    const val PERSONAL_INTERESTS = "trips.createNewTrip.stepHeaders.personalInterests"

    const val SELECT_DESTINATION_CITY = "select_destination_city"
    const val SELECT_START_LOCATION = "select_start_location"
    const val TRIP_WILL_UPDATE = "your_trip_is_going_to_be_updated"
    const val WHAT_TYPE_RESTAURANT = "trips.createNewTrip.restaurantQuestion.title"
    const val LUNCH_BRUNCH = "trips.createNewTrip.restaurantQuestion.lunchBrunch"
    const val DINNER = "trips.createNewTrip.restaurantQuestion.dinner"
    const val PLEASE_SELECT = "trips.myTrips.localExperiences.tourDetails.pleaseSelect"

    // Timeline
    const val RECOMMENDATIONS = "recommendations"
    const val NO_PLANS_FOR_DAY = "no_plans_for_day"
    const val CONFIRMED = "timeline.bookedActivity.confirmed"
    const val RESERVATION = "timeline.bookedActivity.reservation"
    const val VIEW_DETAILS = "view_details"
    const val DELETE_SEGMENT = "delete_segment"
    const val DELETE_SEGMENT_CONFIRM = "delete_segment_confirm"
    const val SAVED_PLANS = "saved_plans"
    const val MAP_VIEW = "map_view"
    const val LIST_VIEW = "list_view"
    const val GENERATING_ITINERARY = "generating_itinerary"
    const val REMOVE_ACTIVITY = "timeline.removeActivity.title"
    const val REMOVE_ACTIVITY_MESSAGE = "timeline.removeActivity.message"
    const val REMOVE_BUTTON = "timeline.removeActivity.remove"
    const val REMOVE_RECOMMENDATIONS = "timeline.removeRecommendations.title"
    const val REMOVE_RECOMMENDATIONS_MESSAGE = "timeline.removeRecommendations.message"
    const val NO_PLANS_YET = "timeline.emptyState.noPlansYet"
    const val NO_PLANS_DESCRIPTION = "timeline.emptyState.noPlansDescription"
    const val ADD_PLANS = "timeline.emptyState.addPlans"
    const val TIMELINE_FORMAT_DISTANCE = "timeline.format.distance"

    // =====================
    // ADD PLAN FLOW
    // =====================

    // Main Actions
    const val ADD_PLAN_TITLE = "addPlan.title.addPlan"
    const val ADD_PLAN_ADD_ACTIVITY = "addPlan.title.addActivity"
    const val ADD_PLAN_CONTINUE = "common.button.continue"
    const val ADD_PLAN_CANCEL = "common.button.cancel"
    const val ADD_PLAN_CONFIRM = "common.button.confirm"
    const val ADD_PLAN_SELECT = "common.button.select"
    const val ADD_PLAN_CLEAR_SELECTION = "addPlan.button.clearSelection"
    const val ADD_PLAN_GENERATE = "addPlan.button.generate"

    // Selection Mode
    const val ADD_PLAN_HOW_TO_ADD = "addPlan.label.howToAddPlans"
    const val ADD_PLAN_SMART_RECOMMENDATIONS = "addPlan.mode.smartRecommendations"
    const val ADD_PLAN_SMART_DESC = "addPlan.description.smartRecommendations"
    const val ADD_PLAN_ADD_MANUALLY = "addPlan.mode.addManually"
    const val ADD_PLAN_MANUAL_DESC = "addPlan.description.addManually"

    // Time & Location
    const val ADD_PLAN_ADD_TO_DAY = "addPlan.label.addToDay"
    const val ADD_PLAN_CITY = "addPlan.label.city"
    const val ADD_PLAN_SELECT_CITY = "addPlan.title.selectCity"
    const val ADD_PLAN_START_TIME = "addPlan.label.startTime"
    const val ADD_PLAN_END_TIME = "addPlan.label.endTime"
    const val ADD_PLAN_TIME = "addPlan.title.time"
    const val ADD_PLAN_SELECT_STARTING_POINT = "addPlan.label.selectStartingPoint"
    const val ADD_PLAN_SELECT_DATE_TIME = "addPlan.label.selectDateAndTime"
    const val ADD_PLAN_SELECT_TIME = "addPlan.label.selectTime"
    const val ADD_PLAN_NO_TIME_SLOTS = "addPlan.label.noTimeSlots"
    const val ADD_PLAN_CONFIRM_ADD_ACTIVITY = "addPlan.message.confirmAddActivity"

    // Categories (Smart Mode)
    const val ADD_PLAN_SELECT_CATEGORIES = "addPlan.label.selectCategories"
    const val ADD_PLAN_CAT_GUIDED_TOURS = "addPlan.category.guidedTours"
    const val ADD_PLAN_CAT_TICKETS = "addPlan.category.tickets"
    const val ADD_PLAN_CAT_EXCURSIONS = "addPlan.category.excursions"
    const val ADD_PLAN_CAT_POI = "addPlan.category.poi"
    const val ADD_PLAN_CAT_FOOD = "addPlan.category.food"
    const val ADD_PLAN_CAT_SHOWS = "addPlan.category.shows"
    const val ADD_PLAN_CAT_TRANSPORT = "addPlan.category.transport"

    // Categories (Manual Mode)
    const val ADD_PLAN_CAT_MANUAL_ACTIVITIES = "addPlan.category.manual.activities"
    const val ADD_PLAN_CAT_MANUAL_PLACES = "addPlan.category.manual.placesOfInterest"
    const val ADD_PLAN_CAT_MANUAL_EAT_DRINK = "addPlan.category.manual.eatAndDrink"

    // Activity Listing
    const val ADD_PLAN_CAT_ALL = "addPlan.category.all"
    const val ADD_PLAN_SEARCH_ACTIVITY = "addPlan.search.activity"
    const val ADD_PLAN_FILTERS = "addPlan.button.filters"
    const val ADD_PLAN_SORT_BY = "addPlan.button.sortBy"
    const val ADD_PLAN_OPINIONS = "addPlan.label.opinions"
    const val ADD_PLAN_FREE_CANCELLATION = "common.label.freeCancellation"
    const val ADD_PLAN_ACTIVITY = "addPlan.label.activity"
    const val ADD_PLAN_ACTIVITIES = "addPlan.label.activities"
    const val ACTIVITIES_FOUND = "addPlan.activitiesFound"

    // Activity Filters
    const val ADD_PLAN_FILTER_TITLE = "addPlan.filter.title"
    const val ADD_PLAN_FILTER_PRICE = "addPlan.filter.price"
    const val ADD_PLAN_FILTER_DURATION = "addPlan.filter.duration"
    const val ADD_PLAN_FILTER_CLEAR = "addPlan.filter.clearSelection"
    const val ADD_PLAN_FILTER_FREE = "addPlan.filter.free"
    const val ADD_PLAN_FILTER_DAYS = "addPlan.filter.days"

    // POI Search
    const val ADD_PLAN_SEARCH_POI = "addPlan.placeholder.searchPOI"
    const val ADD_PLAN_NEAR_ME = "addPlan.option.nearMe"
    const val ADD_PLAN_CITY_CENTER = "addPlan.label.cityCenter"
    const val PLACES_FOUND = "addPlan.placesFound"
    const val ADD_PLAN_TITLE_PLACES_OF_INTEREST = "addPlan.title.placesOfInterest"

    // Other
    const val ADD_PLAN_SELECT_TRAVELERS = "addPlan.label.selectTravelers"
    const val ADD_PLAN_TRAVELERS = "addPlan.label.travelers"
    const val ADD_PLAN_SAVED_ACTIVITIES = "addPlan.section.savedActivities"
    const val ADD_PLAN_EMPTY_SAVED = "addPlan.emptyState.addSavedPlansToItinerary"
    const val ADD_PLAN_SAVED_PLANS = "addPlan.title.savedPlans"
    const val ADD_PLAN_NO_SAVED_PLANS = "addPlan.emptyState.noSavedPlans"
    const val ADD_PLAN_NO_SAVED_PLANS_DESC = "addPlan.emptyState.noSavedPlansDescription"

    // Error Messages
    const val ADD_PLAN_ERROR_MISSING = "trips.myTrips.timelineitinerary.addPlan.error.missingData"
    const val ADD_PLAN_ERROR_CREATE_FAILED = "trips.myTrips.timelineitinerary.addPlan.error.createFailed"

    // =====================
    // POI DETAIL SCREEN
    // =====================

    // Sections
    const val POI_DETAIL_ACTIVITIES = "poiDetail.section.activities"
    const val POI_DETAIL_KEY_DATA = "poiDetail.section.keyData"
    const val POI_DETAIL_MEETING_POINT = "poiDetail.section.meetingPoint"
    const val POI_DETAIL_FEATURES = "poiDetail.section.features"

    // Buttons
    const val POI_DETAIL_SEE_MORE = "poiDetail.button.seeMore"
    const val POI_DETAIL_READ_FULL = "poiDetail.button.readFullDescription"
    const val POI_DETAIL_CLOSE_FULL = "poiDetail.button.closeFullDescription"
    const val POI_DETAIL_VIEW_MAP = "poiDetail.button.viewMap"
    const val POI_DETAIL_CANCEL = "poiDetail.button.cancel"

    // Labels
    const val POI_DETAIL_PHONE = "poiDetail.label.phone"
    const val POI_DETAIL_OPENING_HOURS = "poiDetail.label.openingHours"
    const val POI_DETAIL_CLOSED = "poiDetail.label.closed"
    const val POI_DETAIL_WHERE_STARTS = "poiDetail.label.whereItStarts"
    const val POI_DETAIL_FREE_CANCELLATION = "poiDetail.label.freeCancellation"
    const val POI_DETAIL_FROM = "poiDetail.label.from"

    // Action Sheets
    const val POI_DETAIL_OPEN_IN = "poiDetail.actionSheet.openIn"

    // Legacy keys (still in use)
    const val TIME_AND_TRAVELERS = "time_and_travelers"
    const val STARTING_POINT = "starting_point"
    const val ACCOMMODATION_POINT = "accommodation"
    const val CUSTOM_LOCATION = "custom_location"
    const val GENERATE_RECOMMENDATIONS = "generate_recommendations"
    const val SELECT_POI = "select_poi"
    const val SEE_DO = "see_and_do"
    const val EAT_DRINK = "eat_and_drink"
    const val SPORTS = "sports"
    const val ENTERTAINMENT = "entertainment"

    // =====================
    // SORT OPTIONS
    // =====================
    const val SORT_BY_POPULARITY = "addPlan.sort.popularity"
    const val SORT_BY_RATING = "addPlan.sort.rating"
    const val SORT_BY_PRICE_LOW_HIGH = "addPlan.sort.priceLowToHigh"
    const val SORT_BY_PRICE_HIGH_LOW = "addPlan.sort.priceHighToLow"
    const val SORT_BY_NEWEST = "addPlan.sort.newest"
    const val SORT_BY_DURATION = "addPlan.sort.duration"
    const val SORT_BY_DURATION_LONG_SHORT = "addPlan.sort.durationLongToShort"

    // =====================
    // EMPTY STATES & SEARCH
    // =====================
    const val ADD_PLAN_NO_RECOMMENDATIONS = "addPlan.emptyState.noRecommendations"
    const val POI_SELECTION_ADD_PLACE = "addPlan.button.addPlace"
    const val ADD_PLAN_SEARCH_PLACES_HINT = "addPlan.placeholder.searchPlaces"
    const val POI_SELECTION_NO_PLACES = "addPlan.emptyState.noPlaces"
    const val ACTIVITY_LISTING_NO_ACTIVITIES = "addPlan.emptyState.noActivities"
    const val SEARCH_BAR_HINT = "common.placeholder.search"

    // =====================
    // COMMON UI STRINGS
    // =====================
    const val I_AM_IN = "common.button.iAmIn"
    const val I_AM_OUT = "common.button.iAmOut"
    const val PLEASE_SELECT_FIELD = "common.validation.pleaseSelectField"

}